name: Build Rubix APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk zlib1g-dev libssl-dev build-essential ccache git libffi-dev libltdl-dev libsqlite3-dev
          pip install --upgrade pip
          pip install buildozer kivy

      - name: Auto Accept All Android Licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

      - name: Build APK with Buildozer
        run: |
          yes | buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rubix-apk
          path: bin/*.apk
